### ISSUE TITLE
2.3.5 herokuにpushしたけど

### ISSUE THREAD

**Issue by leonapo** [leonapo/toy_app#9]
```Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.```
ブラウザにこうやってでる。
試しにheroku logsをみたらこう出た。

```keisukenoMBP:toy_app keisukekashiwa$ heroku logs
2018-04-09T12:37:56.129281+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
2018-04-09T12:37:56.129306+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:283:in `start'
2018-04-09T12:37:56.129331+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:44:in `start'
2018-04-09T12:37:56.129355+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:135:in `block in perform'
2018-04-09T12:37:56.129380+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
2018-04-09T12:37:56.129405+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
2018-04-09T12:37:56.129460+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
2018-04-09T12:37:56.129430+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
2018-04-09T12:37:56.129485+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
2018-04-09T12:37:56.129508+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
2018-04-09T12:37:56.129581+00:00 app[web.1]: 	from bin/rails:9:in `require'
2018-04-09T12:37:56.129605+00:00 app[web.1]: 	from bin/rails:9:in `<main>'
2018-04-09T12:37:56.129533+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
2018-04-09T12:37:56.129558+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
2018-04-09T12:37:56.142606+00:00 app[web.1]: => Run `rails server -h` for more startup options
2018-04-09T12:37:56.142600+00:00 app[web.1]: => Booting Puma
2018-04-09T12:37:56.142604+00:00 app[web.1]: => Rails 5.1.4 application starting in production
2018-04-09T12:37:56.142607+00:00 app[web.1]: Exiting
2018-04-09T12:38:09.149509+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=leon-app.herokuapp.com request_id=8eee6d43-4ec2-448b-8d2e-9e7ec1135bc8 fwd="106.181.162.225" dyno= connect= service= status=503 bytes= protocol=https
2018-04-09T12:40:36.000000+00:00 app[api]: Build started by user leon.kashiwa@gmail.com
2018-04-09T12:40:56.171216+00:00 heroku[web.1]: State changed from crashed to starting
2018-04-09T12:40:55.915067+00:00 app[api]: Release v8 created by user leon.kashiwa@gmail.com
2018-04-09T12:40:55.915067+00:00 app[api]: Deploy bccdba88 by user leon.kashiwa@gmail.com
2018-04-09T12:40:36.000000+00:00 app[api]: Build succeeded
2018-04-09T12:40:59.172265+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 30648 -e production`
2018-04-09T12:41:02.637822+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require': /app/app/models/micropost.rb:4: syntax error, unexpected keyword_end (SyntaxError)
2018-04-09T12:41:02.637849+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
2018-04-09T12:41:02.637850+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
2018-04-09T12:41:02.637852+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
2018-04-09T12:41:02.637855+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
2018-04-09T12:41:02.637854+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:379:in `block in require_or_load'
2018-04-09T12:41:02.637857+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
2018-04-09T12:41:02.637858+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
2018-04-09T12:41:02.637860+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
2018-04-09T12:41:02.637861+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `load_interlock'
2018-04-09T12:41:02.637863+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:357:in `require_or_load'
2018-04-09T12:41:02.637865+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:335:in `depend_on'
2018-04-09T12:41:02.637867+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:251:in `require_dependency'
2018-04-09T12:41:02.637868+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
2018-04-09T12:41:02.637870+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `each'
2018-04-09T12:41:02.637872+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `block in eager_load!'
2018-04-09T12:41:02.637873+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `each'
2018-04-09T12:41:02.637878+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `eager_load!'
2018-04-09T12:41:02.637880+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:354:in `eager_load!'
2018-04-09T12:41:02.637881+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:67:in `each'
2018-04-09T12:41:02.637883+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:67:in `block in <module:Finisher>'
2018-04-09T12:41:02.637884+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
2018-04-09T12:41:02.637885+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
2018-04-09T12:41:02.637889+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
2018-04-09T12:41:02.637890+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2018-04-09T12:41:02.637887+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
2018-04-09T12:41:02.637892+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
2018-04-09T12:41:02.637893+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
2018-04-09T12:41:02.637895+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each'
2018-04-09T12:41:02.637898+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
2018-04-09T12:41:02.637896+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `call'
2018-04-09T12:41:02.637901+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
2018-04-09T12:41:02.637899+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
2018-04-09T12:41:02.637904+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
2018-04-09T12:41:02.637902+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
2018-04-09T12:41:02.637912+00:00 app[web.1]: 	from config.ru:3:in `block in <main>'
2018-04-09T12:41:02.637906+00:00 app[web.1]: 	from /app/config/environment.rb:5:in `<top (required)>'
2018-04-09T12:41:02.637907+00:00 app[web.1]: 	from config.ru:3:in `require_relative'
2018-04-09T12:41:02.637914+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
2018-04-09T12:41:02.637915+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
2018-04-09T12:41:02.637917+00:00 app[web.1]: 	from config.ru:in `new'
2018-04-09T12:41:02.637918+00:00 app[web.1]: 	from config.ru:in `<main>'
2018-04-09T12:41:02.637920+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
2018-04-09T12:41:02.637921+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
2018-04-09T12:41:02.637923+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
2018-04-09T12:41:02.637926+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
2018-04-09T12:41:02.637924+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
2018-04-09T12:41:02.637928+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:24:in `app'
2018-04-09T12:41:02.637929+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
2018-04-09T12:41:02.637931+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:283:in `start'
2018-04-09T12:41:02.637932+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:44:in `start'
2018-04-09T12:41:02.637934+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:135:in `block in perform'
2018-04-09T12:41:02.637935+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
2018-04-09T12:41:02.637937+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
2018-04-09T12:41:02.637938+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
2018-04-09T12:41:02.637940+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
2018-04-09T12:41:02.637941+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
2018-04-09T12:41:02.637943+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
2018-04-09T12:41:02.637944+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
2018-04-09T12:41:02.637946+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
2018-04-09T12:41:02.637947+00:00 app[web.1]: 	from bin/rails:9:in `require'
2018-04-09T12:41:02.637951+00:00 app[web.1]: 	from bin/rails:9:in `<main>'
2018-04-09T12:41:02.647591+00:00 app[web.1]: => Booting Puma
2018-04-09T12:41:02.647594+00:00 app[web.1]: => Rails 5.1.4 application starting in production
2018-04-09T12:41:02.647596+00:00 app[web.1]: => Run `rails server -h` for more startup options
2018-04-09T12:41:02.647598+00:00 app[web.1]: Exiting
2018-04-09T12:41:02.719172+00:00 heroku[web.1]: State changed from starting to crashed
2018-04-09T12:41:02.703781+00:00 heroku[web.1]: Process exited with status 1
2018-04-09T12:41:02.882171+00:00 app[api]: Starting process with command `rails db:migrate` by user leon.kashiwa@gmail.com
2018-04-09T12:41:06.587402+00:00 heroku[run.1007]: State changed from starting to up
2018-04-09T12:41:06.427338+00:00 heroku[run.1007]: Awaiting client
2018-04-09T12:41:06.466847+00:00 heroku[run.1007]: Starting process with command `rails db:migrate`
2018-04-09T12:41:13.297083+00:00 heroku[run.1007]: Process exited with status 0
2018-04-09T12:41:13.310811+00:00 heroku[run.1007]: State changed from up to complete
2018-04-09T12:41:21.064124+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=leon-app.herokuapp.com request_id=c3ead94d-ef18-4828-98d6-a3b7536f8042 fwd="106.181.162.225" dyno= connect= service= status=503 bytes= protocol=https```

**解決状態：toy_app が表示されること。**

**Comment by hayashiseiya** [comment]
ローカルではどんな表示になってますか？

**Comment by leonapo** [comment]
1 2 3 4 5 | class User < ApplicationRecord   has_many :microposts   validates FILL_IN, presence: true    # 「FILL_IN」をコードに置き換えてください   validates FILL_IN, presence: true    # 「FILL_IN」をコードに置き換えてください end
-- | --


こんなページがでてます。
